### ISSUE TITLE
Is dumping of secrets to .env is really secure?

### ISSUE THREAD

**Issue by lk-geimfari** [wemake-services/wemake-django-template#1009]
Is dumping of secrets to .env is really secure? Doesn't that mean that anyone who has access to the docker image can see all secrets in it?

What if you have a volunteer developer in a team or something (who has permission to make changes, but can't see our secrets)? Or the question of ensuring this kind of security rests with the system administrator?

Sorry if this question is unrelated. I just want to follow good practices. Thanks!

**Comment by sobolevn** [comment]
No, it is not secure. You should not use this in untrusted env.
Use env vars, docker secrets, configuration providers, vault.

**Comment by lk-geimfari** [comment]
@sobolevn I understand you. I will probably use docker secrets. Thanks for the answer!
