### ISSUE TITLE
Set PYTHONUNBUFFERED

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#103]
Here's a nice explanation on why this might be useful: https://github.com/sclorg/s2i-python-container/issues/157

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,

Just because we started to use Python 3.8 in our template, can we remove `PYTHONUNBUFFERED` variable because starting from Python3.7 _**The text layer of the stdout and stderr streams now is unbuffered.**_ ?(c) https://docs.python.org/3/using/cmdline.html#cmdoption-u

**Comment by sobolevn** [comment]
@DmytroLitvinov yes, please send a PR!
