### ISSUE TITLE
GitLab CI fails on max-line-length=120

### ISSUE THREAD

**Issue by ffedoroff** [wemake-services/wemake-django-template#1030]
When I change max-line-length to 120 in setup.cfg it works perfect on localhost.
`docker-compose run --rm web sh ./docker/ci.sh` works good on localhost as well.
But on GitlabCI it fails:
```
....
[ci started]

./server/urls.py
  0:1      NIP323 File setup.cfg: [isort]line_length is 119 but it should be like this:
[isort]
line_length = 79
  0:1      NIP323 File setup.cfg: [flake8]max-line-length is 120 but it should be like this:
[flake8]
max-line-length = 80
  0:1      NIP322 File setup.cfg has missing values in the 'ignore' key. Include those values:
[flake8]
ignore = (...),DAR203

Full list of violations and explanations:
https://wemake-python-stylegui.de/en/0.13.3/pages/usage/violations/
ERROR: Job failed: exit code 1
```
Could you please suggest how to fix that issue?

**Comment by sobolevn** [comment]
It is related to `nitpick` configuration in `pyproject.toml`
See: https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/nitpick.html

But, I do not recommend to change this setting. Line length is not a stylistic choice, it is a complexity metric. Read this: https://sobolevn.me/2019/10/complexity-waterfall

**Comment by ffedoroff** [comment]
I'm sorry to bother you again. I read info on both links. But I'm still not clear how to fix build on GitLab? How properly configure `nitpick` to use my own overrides in `pyproject.toml`?

**Comment by sobolevn** [comment]
You can either remove `[tool.nitpick]` from `pyproject.toml` and uninstall `nitpick` or create your own config based on this one: https://github.com/wemake-services/wemake-python-styleguide/blob/master/styles/nitpick-style-wemake.toml

You need to change this line: https://github.com/wemake-services/wemake-python-styleguide/blob/master/styles/styleguide.toml#L8

**Comment by ffedoroff** [comment]
Thank you very much. I will try it!
