### ISSUE TITLE
Update django to 2.2.9

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1033]
Dependabot is not working for now
Link: https://www.djangoproject.com/weblog/2019/dec/18/security-releases/

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,

It is already 2.2.9 version in [poetry.lock file](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/poetry.lock#L235)
