### ISSUE TITLE
Caddy image uses deprecated letsencrypt ACME API

### ISSUE THREAD

**Issue by damienallen** [wemake-services/wemake-django-template#1049]
I'm currently unable to use the production docker-compose configuration supplied in the template. Running the configuration results in the following error:

> registration error: acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

Key details from the link:

> In **November of 2019** we will stop allowing new account registrations through our ACMEv1 API endpoint. Existing accounts will continue to function normally.

> In **June of 2020** we will stop allowing new domains to validate via ACMEv1.

> In **June of 2021** we will entirely disable ACMEv1 as a viable way to get a Let’s Encrypt certificate.

I found [this discussion](https://caddy.community/t/problem-with-old-caddy-version-ssl-not-provided/6752/3), which suggests that the latest caddy v1 release will not have this issue.

**Comment by sobolevn** [comment]
Oh shiii, that's bad. As a workaround you can update the image version locally.

I will try to find full solution. Related #36

**Comment by damienallen** [comment]
I'm looking into Caddy2 or alternatives. Should have put it in the original post but my main concern is the renewals ending next year for existing image users. 

Serving static files is important for my use case so I'm leaning away from Traefik.

**Comment by folt** [comment]
I am using HAProxy. During this time, he worked without breakdowns.

**Comment by sobolevn** [comment]
@folt does it have 

1. static files serving mechanism?
2. automatic https?

**Comment by folt** [comment]
> static files serving mechanism?
Yes, it can give away static files. But I would prefer to proxy a request to a service that is designed for this better.

> automatic https?
No, required certbot
