### ISSUE TITLE
show link to the error code like eslint

### ISSUE THREAD

**Issue by jnoortheen** [wemake-services/wemake-django-template#1067]
It will be easier to understand the errorcode if there is link to the documentation from the terminal itself. It will help the new developers in the team and also saves time googling. It can be added at the end next to each errors when the combined error count is shown.

**Comment by jnoortheen** [comment]
wrong place. wanted to raise in styleguide repo.

**Comment by sobolevn** [comment]
@jnoortheen it might be related: https://github.com/wemake-services/wemake-python-styleguide/issues/1145
