### ISSUE TITLE
Gunicorn settings do not apply

### ISSUE THREAD

**Issue by theoden-dd** [wemake-services/wemake-django-template#1143]
And haven't been working for about 4 months: https://github.com/wemake-services/wemake-django-template/blame/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/gunicorn.sh#L32

According to https://stackoverflow.com/a/23591495/10976040 and practice.

**Comment by sobolevn** [comment]
@theoden-dd oh! Can you please send the fix?

**Comment by theoden-dd** [comment]
Will do slightly later.
