### ISSUE TITLE
Django 3 Support

### ISSUE THREAD

**Issue by zwass** [wemake-services/wemake-django-template#1189]
What would it take to update this to work with Django 3?

According to https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/, Django 2.2 is "out of mainstream support", which makes me very hesitant to start any new project with it.

**Comment by sobolevn** [comment]
> Django 2.2 is an LTS release and will receive security and data loss fixes until April 2022

We only using LTS releases of Django in our company. So, the next update will be 3.2
But, you can update freely to 3.1 inside your own app, it should be a matter of one command.
