### ISSUE TITLE
Django@3.1 support

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1258]
New LTS version is out. We need to research how our dependencies behave with it.
I know that `django-stubs` do not fully support `3.1` yet.

**Comment by DmytroLitvinov** [comment]
Hey @sobolevn ,

Django `3.1` is not LTS version.
Please, see [it here](https://www.djangoproject.com/download/).

**Comment by sobolevn** [comment]
Thanks @DmytroLitvinov! Closing
