### ISSUE TITLE
Support gitlab-pages

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#131]
There should be a research:
- can pages be private
- can we build pages inside CI
- does gitlab support sphinx

Links:
- https://gitlab.com/pages/sphinx
- https://gitlab.com/help/user/project/pages/index.md
- https://gitlab.com/gitlab-org/gitlab-ce/issues/33422

**Comment by sobolevn** [comment]
Right now private pages are not supported. We can wait for this to be merged: https://gitlab.com/gitlab-org/gitlab-ce/issues/33422

**Comment by sobolevn** [comment]
Progress https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-access-control-core-only

**Comment by AlwxSin** [comment]
- [X] can we build pages inside CI
- [X] does gitlab support sphinx

I made a publish stage on our private gitlab. @sobolevn I can handle this.

**Comment by sobolevn** [comment]
gitlab.com still does not support private docs. But, having an example is always good!
So, please send your solution.
