### ISSUE TITLE
Entrypoint.sh breaks quotes

### ISSUE THREAD

**Issue by theoden-dd** [wemake-services/wemake-django-template#1312]
### Steps to reproduce

Run `docker-compose run --rm web python3 -c 'import secrets; print(secrets.token_urlsafe(50))'`

### Actual behavior

It complains on single "import" word (breaks at space).

### Expected behavior

It should print a hash.

### Considerations

As a workaround we can use `docker-compose run --rm --entrypoint "python3 -c 'import secrets; print(secrets.token_urlsafe(50))'" -- web`, but that's ugly.

I wonder why do we need the [cmd variable](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/entrypoint.sh#L6) at all?

I changed `exec $cmd` to `exec "$@"` directly and that fixed the bug.

Any known issues with that solution?

**Comment by sobolevn** [comment]
I don't know! 🙂 

Let's remove it.

**Comment by DmytroLitvinov** [comment]
Btw, we can generate `SECRET_KEY` from django's code:
`python3 -c 'from django.core.management.utils import get_random_secret_key; get_random_secret_key()'`
