### ISSUE TITLE
ReadTheDocs should use Pipfile

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#133]
Right now we are using a special `doc/requirements.txt` file for readthedocs.
There should be a way to install dependencies from `Pipfile`.

https://github.com/rtfd/readthedocs.org/issues/3181

**Comment by sobolevn** [comment]
Closing, we are not using `Pipfile` anymore.

**Comment by DmytroLitvinov** [comment]
Wow. So quick changes in the project. Niceee :muscle:
