### ISSUE TITLE
Consider using django-extra-checks

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1334]
It is pure gold! 👍 

https://github.com/kalekseev/django-extra-checks

Thanks a lot to @kalekseev for building it!

**Comment by kalekseev** [comment]
Thanks, I still need to write better docs and add ability to ignore specific warnings but overall we've used it for several months and it works really well. If you have any good ideas for more checks then I'm ready to discuss them.

**Comment by sobolevn** [comment]
> If you have any good ideas for more checks then I'm ready to discuss them.

Yes, I have several in mind. I will open new issues 👍
