### ISSUE TITLE
flake8 ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by folt** [wemake-services/wemake-django-template#1340]
when using the command
`flake8 .`

I get an error: 
```
.........
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```
my python version - 3.7.8
my poetry version - 1.1.3

**Comment by sobolevn** [comment]
We have updated to `3.8` already. So, I am going to close this.

Solution for you: add `importlib-metadata` as a dependency.
