### ISSUE TITLE
Update Caddy image to 2.2 for production build

### ISSUE THREAD

**Issue by DmytroLitvinov** [wemake-services/wemake-django-template#1398]
Hi @sobolevn ,

I would like to propose you to use Caddy `2.2` in this [line of code](https://github.com/wemake-services/wemake-django-template/blob/421fd2325cd293bde598654fe6f2608dbef41927/%7B%7Bcookiecutter.project_name%7D%7D/docker/docker-compose.prod.yml#L12). What do you think about it?

**Comment by sobolevn** [comment]
Sure, prs are welcome!
