### ISSUE TITLE
Update to `poetry@1.2`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1666]
We will be able to move `doc` dependencies to a separate group: https://python-poetry.org/blog/announcing-poetry-1.2.0a2/

**Comment by sobolevn** [comment]
Looks like with new `poetry` we will be able to get rid off `requirements.txt` for readthedocs! 🎉 

Example: https://github.com/TeoZosa/structlog-sentry-logger/commit/b53acbfe0cc4289378e6195a4c1351709a1909a3

@DmytroLitvinov do you want to try this? 🙂

**Comment by sobolevn** [comment]
Related https://github.com/wemake-services/wemake-django-template/issues/572

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,
Sure, I can try.

**Comment by sobolevn** [comment]
I've just found out that it is not yet released 🙂

**Comment by DmytroLitvinov** [comment]
Thanks for that important note :)
