### ISSUE TITLE
Support for Apple M1 (aarch64)

### ISSUE THREAD

**Issue by craastad** [wemake-services/wemake-django-template#1725]
Currently [dockerize](https://github.com/jwilder/dockerize) does not support aarch64 [Issue](https://github.com/jwilder/dockerize/issues/143), which makes it impossible to run the sample project on Mac M1. I've also tried using [rosetta](https://earthly.dev/blog/using-apple-silicon-m1-as-a-cloud-engineer-two-months-in/) to run docker on an emulated terminal (`arch -arch arm64 docker-compose up`), but it did not.

Relevant error message snippet:
```
#8 34.39 /lib64/ld-linux-x86-64.so.2: No such file or directory
------
executor failed running [/bin/sh -c apt-get update && apt-get upgrade -y   && apt-get install --no-install-recommends -y     bash     build-essential     curl     gettext     git     libpq-dev     $BUILD_ONLY_PACKAGES   && wget "https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz"   && tar -C /usr/local/bin -xzvf "dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz"   && rm "dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz" && dockerize --version   && wget -O /usr/local/bin/tini "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini"   && chmod +x /usr/local/bin/tini && tini --version   && curl -sSL 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py' | python   && poetry --version   && apt-get remove -y $BUILD_ONLY_PACKAGES   && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false   && apt-get clean -y && rm -rf /var/lib/apt/lists/*]: exit code: 255
ERROR: Service 'web' failed to build : Build failed
```

**Comment by mschoettle** [comment]
I got this error in regards to `tini`. If the download URL for `tini` is changed to `tini-arm64` it works.
The best would be to download the binary according to the architecture as shown here: https://github.com/krallin/tini/issues/177#issuecomment-768637877

**Comment by sobolevn** [comment]
@mschoettle PR would be very much welcome!

**Comment by mschoettle** [comment]
@craastad Can you confirm whether #1843 fixes your issue?

**Comment by sobolevn** [comment]
@craastad please, reopen if this won't work for you.
