### ISSUE TITLE
Update http.limits settings

### ISSUE THREAD

**Issue by Kotenkov** [wemake-services/wemake-django-template#195]
It is needed to increase limits on HTTP requests.

**Comment by sobolevn** [comment]
Invalid, since there is no limit be default. https://caddyserver.com/docs/limits

> Request body sizes can also be limited. When the number of bytes read from a request body exceeds the limit, reading will terminate and an error will be sent to the client. (Technically, it depends on	each middleware that reads a request body to handle the error properly, but standard Caddy directives should respond with HTTP 413.) By default, there is no size limit.
