### ISSUE TITLE
Expected type 'Type[BindableLogger] | None', got 'Type[BoundLogger]' instead

### ISSUE THREAD

**Issue by folt** [wemake-services/wemake-django-template#2022]
There is a linter error in the logs. Types do not match.
![image](https://user-images.githubusercontent.com/3757488/179318293-16857238-bfff-4f76-b272-1925665e1dd2.png)

**Comment by sobolevn** [comment]
Do you have a fix in mind?

**Comment by sobolevn** [comment]
One more thing: looks like this only happens in PyCharm?

**Comment by folt** [comment]
> One more thing: looks like this only happens in PyCharm?

Apparently this is only a PyCharm issue. I'm still researching to suggest the best fix.
