### ISSUE TITLE
[docs] Mention of `sql/` folder - is still available?

### ISSUE THREAD

**Issue by DmytroLitvinov** [wemake-services/wemake-django-template#2116]
Hi @sobolevn ,

In [overview page](https://wemake-django-template.readthedocs.io/en/latest/pages/template/overview.html#config) there is a mention of `sql/` folder which is not created in project with .gitkeep.

Do we still mention it?

**Comment by sobolevn** [comment]
Yeah, we should remove mentions of it :)
