### ISSUE TITLE
Change path for CaddyFile in docker-compose.prod.yml

### ISSUE THREAD

**Issue by Tshibek** [wemake-services/wemake-django-template#2139]
When you try deploy app with that config Caddyfile will be not read so
in docker-compose.prod.yml you need change that line
`- ./docker/caddy/Caddyfile:/srv/Caddyfile  # configuration`
to
`- ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile`

**Comment by sobolevn** [comment]
Yes, please! Send a PR :)
