### ISSUE TITLE
Add logging tests

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#2366]
This problem (https://github.com/wemake-services/wemake-django-template/commit/53ae125a0e2eed88f7b36a5edd07591ba0401b24) identified that our logging configuration was and is not tested at all.

We need to add tests for it:
- We need to test regular logging format
- We need to test exception logging format

Please, feel free to send PRs :)

**Comment by Tejoooo** [comment]
@sobolevn can u assign me this issue
