### ISSUE TITLE
Missing csp middleware

### ISSUE THREAD

**Issue by CompadreP** [wemake-services/wemake-django-template#261]
Guys, I see you are using django-csp and it looks like you forgot to add 'csp.middleware.CSPMiddleware'  to middlewares list like it noted in installation guide - http://django-csp.readthedocs.io/en/latest/installation.html

**Comment by sobolevn** [comment]
Oups! @CompadreP can you please send a PR?

**Comment by sobolevn** [comment]
Closed via #263
