### ISSUE TITLE
Add notes about save DJANGO_SECRET_KEY env in Gitlab CI

### ISSUE THREAD

**Issue by pygo** [wemake-services/wemake-django-template#320]
Add notes how transfer DJANGO_SECRET_KEY env var to gitlab CI

1.  Go to Gitlab -> Settings -> CI \ CD -> Secret Variables
2. Add a secret var on the rules of dump-env (by default -> SECRET_DJANGO_SECRET_KEY)
3. Save

**Comment by sobolevn** [comment]
@pygo are you interested in providing a fix? It would be very nice!

Thanks for the reporting.

**Comment by pygo** [comment]
@sobolevn OK! Today or tomorrow.

**Comment by pygo** [comment]
#322
