### ISSUE TITLE
[mypy-server.*.migrations.*] does not work anymore

### ISSUE THREAD

**Issue by pygo** [wemake-services/wemake-django-template#334]
``setup.cfg: [mypy-server.*.migrations.*]: Invalid pattern. Patterns must be 'module_name' or 'module_name.*'``
Issue in mypy (https://github.com/python/mypy/issues/5014)

**Comment by sobolevn** [comment]
Thanks, @pygo ! I have already seen it in some real-world apps.
But I had no chance to fix it.
