### ISSUE TITLE
Add django-axes model backend

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#336]
Docs: https://django-axes.readthedocs.io/en/latest/configuration.html
Source: https://github.com/jazzband/django-axes/blob/master/axes/backends.py

**Comment by sobolevn** [comment]
https://github.com/jazzband/django-axes/issues/340#issuecomment-388408857

**Comment by DmytroLitvinov** [comment]
Also had the same problem :(
Do you really use this package for production apps?
Maybe let's take it away?

**Comment by DmytroLitvinov** [comment]
Or just write documentation about current problem in future?

**Comment by sobolevn** [comment]
Yes, I am using `django-axes` for a very long time. It won't be removed.
However, I will make some additions to configuration and documentation to bind them together.

**Comment by sobolevn** [comment]
https://github.com/jazzband/django-axes/issues/340#issuecomment-388538626

**Comment by sobolevn** [comment]
Actually, after testing it in production, we won't add it.
This gives two much confusion, overrides production configuration with an extreme change, and gives almost no gain.
