### ISSUE TITLE
root owns pre-commit artifacts

### ISSUE THREAD

**Issue by apt-ma** [wemake-services/wemake-django-template#340]
Is that normal (when docker and pipenv shell enabled)?
![screen](https://user-images.githubusercontent.com/22030448/39968479-01493f6e-56d6-11e8-9d14-64f631f7ccb8.png)

**Comment by sobolevn** [comment]
Nope, that's not normal. Do you have any specific settings?
I guess it is `docker` specific issue.

**Comment by apt-ma** [comment]
I think so. Docker installed from official repo via `apt`, current user is a member of `docker` group.
I wonder why these files are created in project directory, not in container.
https://github.com/wemake-services/wemake-django-template/blob/a6de055c250a332780c25a966eb8b40c27dd2c98/%7B%7Bcookiecutter.project_name%7D%7D/.pre-commit-config.yaml#L13

**Comment by sobolevn** [comment]
Because that's how volumes are mounted. https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.yml#L29

Maybe tweaking with `.dockerignore` will solve it?

**Comment by apt-ma** [comment]
Maybe it's just mutually exclusive operations?
https://github.com/wemake-services/wemake-django-template/blob/a6de055c250a332780c25a966eb8b40c27dd2c98/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.yml#L28-L29
https://github.com/wemake-services/wemake-django-template/blob/a6de055c250a332780c25a966eb8b40c27dd2c98/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/Dockerfile#L38
I have removed the first one, and it seems to work.

**Comment by sobolevn** [comment]
Hm, since we:
1. store media and static files in their own volumes
2. write logs into stdout instead of file
3. store `caddy` certs inside it's own volume: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/docker-compose.prod.yml#L16

It is safe to say, that we don't really need `.:/code ` part.
@apt-ma thanks a lot! Are you willing to send a PR?

**Comment by sobolevn** [comment]
@apt-ma this way we even do not need to clean everything up inside `ci.sh`.
That can be removed too.

**Comment by apt-ma** [comment]
Yes, for sure.
