### ISSUE TITLE
root owns pre-commit artifacts

### ISSUE THREAD

**Issue by apt-ma** [wemake-services/wemake-django-template#345]
Details are here: #340

**Comment by apt-ma** [comment]
Since we clean cache _before_ CI:
https://github.com/wemake-services/wemake-django-template/blob/e4dc48841b600662a6b1931c868c826933243b16/%7B%7Bcookiecutter.project_name%7D%7D/docker/ci.sh#L70-L76
What if in development we will clean cache _after_ CI?

**Comment by sobolevn** [comment]
After `ci.sh` is finished it should be cleaned also: by `trap pyclean EXIT INT TERM`.
Could you please double check that this is executed?

**Comment by sobolevn** [comment]
https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine#avoiding-permission-changes-when-sharing-volumes

**Comment by sobolevn** [comment]
@apt-ma Could you please try to provide `USEDID` env var inside `docker-compose.yml` and run the tests?

**Comment by apt-ma** [comment]
You're right, it's a feature of Linux systems. I resolved this like [that](https://gitlab.com/aptma/nordwinst/commit/f89df2c13656bb97c4f63655ddd9aa91eb6104e3).

**Comment by sobolevn** [comment]
Nice! Could you please make a link from the docs to this issue? 
I guess this place is the best one: http://wemake-django-template.readthedocs.io/en/latest/_pages/template/docker.html#common-issues

**Comment by sobolevn** [comment]
I will copy the fix here for history reasons:

```diff
# .pre-commit-config.yaml

-      entry: docker-compose run -e INSIDE_CI=0 web sh ./docker/ci.sh
+      #entry: docker-compose run -e INSIDE_CI=0 web sh ./docker/ci.sh
+      entry: bash ./docker/precommit.sh
```

```diff
# .docker-compose.yml

          DJANGO_DATABASE_HOST: db
+     user: ${CURRENT_UID}
    command: python -Wd manage.py runserver 0.0.0.0:8000

```

```diff
# docker/precommit.sh  

+ #!/usr/bin/env bash
+ 
+ CURRENT_UID=$(id -u):$(id -g) docker-compose run -e INSIDE_CI=0 web sh ./docker/ci.sh
```
