### ISSUE TITLE
Let's do lint and autoformat SQL migrations scripts

### ISSUE THREAD

**Issue by kxepal** [wemake-services/wemake-django-template#385]
**Why?**

- Because we don't want to see `NULL` and `null` in the same script;
- Because we don't want to deal with inconsistent align of long scripts;
- Because we don't want to think should brackets be delimited by space or not;
- Because we don't want to be disturbed by a shape and want to focus on what it contains;

**How?**

https://www.sqlstyle.guide/

Suddenly, there are no known implementations for Python. That's should be an interesting task.

**Comment by sobolevn** [comment]
That's a challenging task indeed. 
Related: https://pypi.org/project/format-sql/

**Comment by sobolevn** [comment]
Sorry, but this is out of scope of the project.

There are no tools that allow that at the moment. So, it would not be easy to implement.
