### ISSUE TITLE
Let's lint Python migrations

### ISSUE THREAD

**Issue by kxepal** [wemake-services/wemake-django-template#386]
It's still the code which should have a style, be well formed, no typos and gotchas. 

Follows: #385

**Comment by sobolevn** [comment]
That's really a good idea, I do not know why I have missed it.

**Comment by theoden-dd** [comment]
What is the real profit of linting migrations?

They are an echo of the models well-linted already. They are auto-generated and all manual special-for-linters editing is broken with a regeneration.

I absolutely agree with migration-specific checks. They're cool and must have. 

But general beauty and consistency linting which auto-generator doesn't comply with - why isn't this just a waste of time?

**Comment by sobolevn** [comment]
@theoden-dd not all migrations are generated. All data-migrations are written by hand.
Moreover, regenerating migration files? I don't think that this happens frequently.
