### ISSUE TITLE
Consider adding links check

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#403]
I am not sure about how it works.
https://github.com/aws/chalice/blob/b6312f75b501bd83527a03d978b6b6cb850dabb6/docs/Makefile

**Comment by DmytroLitvinov** [comment]
It does fit for this project, Nikita?

**Comment by sobolevn** [comment]
It does not work 🙂 

I have spent a lot of time trying to actually make it work, but no success.
Feel free to reopen if the solution exists.
