### ISSUE TITLE
Segfault when using python_autoreload

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#42]
For some reason I have now started to receive segmentation fault errors in development. It does not happen all the time. Just happens at some unpredictable cases.

I have found two solutions (hacks):
1. Add `--noreload` option to `runserver` command
2. Add `import threading; threading.stack_size(2*1024*1024)  # noqa` to the top level of `manage.py`

Waiting this issue to be fixed: https://bugs.alpinelinux.org/issues/8134
Also related: https://github.com/docker-library/python/issues/211

**Comment by ncopa** [comment]
Does it make any difference if you add `ENV JSON_MAX_STACK_BUFFER_SIZE=1024` before running `pip`?

**Comment by sobolevn** [comment]
@ncopa I will test this settings shortly, thanks.

**Comment by sobolevn** [comment]
@ncopa nope, it did not work. 

But `import threading; threading.stack_size(2*1024*1024)` works. 
So, I have tried to increase `JSON_MAX_STACK_BUFFER_SIZE`'s value to `2048`.
And it still fails. I guess it happens, because `JSON_MAX_STACK_BUFFER_SIZE` setting is specific to `ujson`, while I having trouble with `django_rest_framework`.
