### ISSUE TITLE
Add a note into `.env.template` about a way to generate secret keys

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#424]
Now: https://github.com/wemake-services/wemake-django-template/blob/40b499b0362b1e26bb0aa1e99018090a2e2a943b/%7B%7Bcookiecutter.project_name%7D%7D/config/.env.template#L12-L14
It should be:

```cfg
# === Django ===
# Generate yours with:
# python3 -c 'import secrets; print(secrets.token_hex(50))'

DJANGO_SECRET_KEY=__CHANGEME__
```

**Comment by theoden-dd** [comment]
@sobolevn , just as an idea: why not to use [token_urlsafe](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe)?
Wouldn't it provide better entropy due to its extended character set?
