### ISSUE TITLE
Consider adding local HTTPS

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#458]
https://twitter.com/getify/status/1023202051902373888

But, I don't know how this can be easily achieved.

**Comment by sobolevn** [comment]
https://github.com/FiloSottile/mkcert works fine.

**Comment by sobolevn** [comment]
That's too complicated for the newcomers.

**Comment by DmytroLitvinov** [comment]
Hey @sobolevn .

Have you ever needed it once locally HTTPS at your work?
