### ISSUE TITLE
Possible restructure, create `server/apps/` directory

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#46]
Would our template benefit from moving apps into `server/apps/` directory?

I can see several benefits:
- It would be easy to integrate `coverage` and `pylint`
- It would be easy to ingrate `setup.py`
- Cleaner directory structure

Cons:
- Not a default `django` structure

**Comment by lapshin1988** [comment]
I think it is a good idea! Because apps and settings it is different entities. Separating provides a more clear structure

**Comment by sobolevn** [comment]
@lapshin1988 thanks for bringing this up! Agreed.
