### ISSUE TITLE
Change link in comment

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-django-template#464]
There is a [line](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L59) in `setup.cgf`.
It contains link to bit.ly service which leads to mypy official documentation. However other link in file leads directly to official resourses.

Is it normal or special case? Can I send PR ?

**Comment by sobolevn** [comment]
I guess I have copied it from somewhere.
@AlwxSin please send a PR with the fix.
