### ISSUE TITLE
Enable "Referrer-Policy" header with "no-referrer" value

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#543]
There's a plugin for that: https://pypi.org/project/django-referrer-policy/

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by sobolevn** [comment]
This should be added back again when `django-referrer-policy` will work with `django@2.2`
Original issue: https://github.com/ubernostrum/django-referrer-policy/pull/3

**Comment by sobolevn** [comment]
Actually this package has a lot of problems inside: 
1. It ships `runtests.py` and `tests/` folder
2. It does not support django1.11 for our old users
3. The last release was 1 year ago
4. The whole package consists of just one file

**Comment by sobolevn** [comment]
A fork maybe?

**Comment by DmytroLitvinov** [comment]
Why do not integrate as own middleware inside project with new style of middleware?

**Comment by sobolevn** [comment]
I do not like to have boilerplate in my projects.
It is better to create a new maintainable project for this.

Requirements:
1. It should be tested with latest django releases and LTS ones
2. Python3.5 (6?)+ support
3. Available on PyPI

@DmytroLitvinov it might be a good one-day project if you want to take this!

**Comment by sobolevn** [comment]
Ok, closing as unsolved. We are not going to use `django-referrer-policy` because it is unmaintained.

**Comment by DmytroLitvinov** [comment]
@sobolevn we could install it via pypi.
It is fork of origin library.
https://pypi.org/project/django-http-referrer-policy/

**Comment by sobolevn** [comment]
@DmytroLitvinov PR is welcome!
