### ISSUE TITLE
ReadTheDocs should support `pyproject.toml`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#572]
This is a substitute for: https://github.com/wemake-services/wemake-django-template/issues/133
Original issue about `Pipfile`: https://github.com/rtfd/readthedocs.org/issues/3181
Original issue about `poetry`: https://github.com/rtfd/readthedocs.org/issues/4912

Currently we have to keep additional `requirements.txt` file, because readthedocs cannot use `pyproject.toml` and `poetry`.

**Comment by sobolevn** [comment]
`pip@19` is almost ready to be released:  https://github.com/pypa/pip/milestone/30

**Comment by DmytroLitvinov** [comment]
Pip 19 was released :tada:

**Comment by sobolevn** [comment]
It still does not support `[dev-dependencies]` section.
