### ISSUE TITLE
Create "Security" section in the docs

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#587]
There are a lot of security topic that we cover in this template.
However, they are not documented well enough. 

We need to list: 
- principles that we enforce
- audition tools like `twa` and https://github.com/s0md3v/XSStrike
- internal settings and custom middleware that we use for improved security
- 3rd party apps: bundled and recommended, like `django-axes` and `django-honeypot`
- security checks that we execute on each CI build

**Comment by sobolevn** [comment]
Hey, @Insaida! Do you have some time to review our security docs?

You can have a look here: https://wemake-django-template.readthedocs.io/en/latest/pages/template/security.html

Is there anything that we are missing? 🙂

**Comment by Insaida** [comment]
Hi @sobolevn Sure. I would do a review this weekend. Would that be fine?

Top off, I see some necessary things already in place. 

Nice work.

**Comment by sobolevn** [comment]
Sure, thanks!
