### ISSUE TITLE
Question about Caddyfile proxy `web:8000`

### ISSUE THREAD

**Issue by zbjdonald** [wemake-services/wemake-django-template#594]
Forgive for this newbie question. I use docker stack to test deploy my project with a local machine in production mode. My understanding is that request goes to Caddy docker throw 80 or 433 port, and Caddy container proxy to web container?

Why prefer `web:8000` to `localhost:8000`? Is it related to docker network settings or some load balance thinking?
https://github.com/wemake-services/wemake-django-template/blob/4e14ef8f26392baa34656681028a6ff2da3ae4ea/%7B%7Bcookiecutter.project_name%7D%7D/docker/caddy/Caddyfile#L17

**Comment by sobolevn** [comment]
Yes, it is related to docker networks. See https://docs.docker.com/compose/networking/

`localhost` inside the container is just this container (well, it is actually more complicated than that, see https://docs.docker.com/compose/compose-file/#network-configuration-reference).

So, `web:8000` is a valid reference to all `django` containers you have.
