### ISSUE TITLE
Keeping Django database migrations backward compatible

### ISSUE THREAD

**Issue by DmytroLitvinov** [wemake-services/wemake-django-template#634]
After reading this post: https://medium.com/3yourmind/keeping-django-database-migrations-backward-compatible-727820260dbb

Maybe we should add next libraries:
* https://github.com/3YOURMIND/django-add-default-value
* https://github.com/3YOURMIND/django-deprecate-fields
* https://github.com/3YOURMIND/django-migration-linter

**Comment by sobolevn** [comment]
Sure, I will keep an eye on it.

**Comment by DmytroLitvinov** [comment]
@sobolevn this is quite good as you said for doing rollback migration.

Maybe add this to section ["Linters that are not included"](https://wemake-django-template.readthedocs.io/en/latest/pages/template/linters.html#linters-that-are-not-included) add write warning that it has slow speed of checking?

**Comment by sobolevn** [comment]
Sounds like a plan!

**Comment by sobolevn** [comment]
@DmytroLitvinov do you want to send a PR for this?

**Comment by DmytroLitvinov** [comment]
@sobolevn, yes, I want.
Let me 1-2 days for that :)
I am going to assign it to myself.

**Comment by DmytroLitvinov** [comment]
Hey @sobolevn .
I am not sure that we still need these packages cause of upgrading to Django 2.2 and they are not so popular and required for this template.

What do you think?

**Comment by sobolevn** [comment]
Sorry, I don't understand how this package is related to our upgrade to 2.2:
- is this now a feature of 2.2?
- is 2.2 not supported by the package?

**Comment by DmytroLitvinov** [comment]
I thought that one of these packages will check deprecations even for upgrading from Django 1.11 and Django 2.2. Seems like they do another work as I see right now after reading their READMEs. 

Just to be sure: do we still need these packages in templates? I have no practice with these packages in real projects. Just found at Medium blog.

**Comment by DmytroLitvinov** [comment]
Ahh... okay.
