### ISSUE TITLE
Consider dennis

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#637]
https://github.com/willkg/dennis/

It is similar to `polint`, we need to find out which one is better.

**Comment by sobolevn** [comment]
Related: https://github.com/willkg/dennis/issues/106

We provide this snippet as a work-around:

```bash
if find locale -name '*.po' -print0 | grep -q "."; then
    # Only executes when there is at least one `.po` file:
    dennis-cmd lint --errorsonly locale
fi
```

**Comment by DmytroLitvinov** [comment]
Thanks for your comment about each issue, Nikita.
