### ISSUE TITLE
Add django-healthcheck

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#644]
https://github.com/KristianOellegaard/django-health-check

**Comment by DmytroLitvinov** [comment]
Nice package.
Where did you find it?

**Comment by DmytroLitvinov** [comment]
ping @sobolevn

**Comment by sobolevn** [comment]
Somewhere in google. I recently had manually updated two mine projects with a healthcheck endpoint.
So, I understood that it is useful to be included into the core template.

**Comment by DmytroLitvinov** [comment]
Thanks!
