### ISSUE TITLE
Consider adding a makefile

### ISSUE THREAD

**Issue by hermanocabral** [wemake-services/wemake-django-template#645]
Hi,

Would you be interested in using a makefile to abstract the commands used during development, things like _python manage.py migrate_, _psql postgres -f sql/create_database.sql_, etc.?

I think makefiles are great because:

1. They are supported pretty much everywhere.
2. They abstract just enough to make the developer's life easier without resorting into **magic** (hiding what's being done or how it's being done).
3. They standardize the development workflow. Wanna create a database? _make createdatabase_. Collect static files? _make django-collectstatic_.

**Comment by sobolevn** [comment]
@hermanocabral I really have dualistic view on `Makefile`s. I tend to write them a lot, but then I found myself ignoring them and doing everything by hand.

But, I would be happy to review a PR with a `Makefile`. It might be very helpful for beginners. To overview all commands and learn how to invoke them.

A technical detail: commands should work with both local setup and `docker`.

**Comment by AlwxSin** [comment]
I leave here an example of my Makefile

```
PWD = $(shell pwd)
BASE_RUN_CMD = docker-compose run --rm

makemigrations:
	$(BASE_RUN_CMD) web ./manage.py makemigrations

migrate:
	$(BASE_RUN_CMD) web ./manage.py migrate

test: 
	$(BASE_RUN_CMD) -e INSIDE_CI=0 web sh ./docker/ci.sh

example_run_specific_test:
	@echo "$(BASE_RUN_CMD) web pytest --lf  <- run tests that failed on last run"
	@echo "$(BASE_RUN_CMD) web pytest tests/test_matches/  <- all test in folder"
	@echo "$(BASE_RUN_CMD) web pytest tests/test_matches/test_match_views.py  <- all test in file"
	@echo "$(BASE_RUN_CMD) web pytest tests/test_matches/test_match_views.py::test_match_filter_by_tour  <- specific test"
	@echo "$(BASE_RUN_CMD) web pytest --runslow -n3 --cov=backend --cov-config=.coveragerc --cov-report=html  <- run coverage report"

pg_dump:
	docker-compose exec db sh -c 'PGHOST=localhost PGPASSWORD=${POSTGRES_PASSWORD} PGUSER=${POSTGRES_USER} PGBASE=${POSTGRES_DB} pg_dump -c | gzip > /tmp/pg_backup/db.pgsql.gz'

pg_restore:
	docker-compose exec db sh -c 'gunzip -c /tmp/pg_backup/db.pgsql.gz | PGHOST=localhost PGPASSWORD=${POSTGRES_PASSWORD} PGUSER=${POSTGRES_USER} PGBASE=${POSTGRES_DB} psql'
```

**Comment by jnoortheen** [comment]
I propose using a Pythonic tool [Invoke](http://www.pyinvoke.org/)

**Comment by sobolevn** [comment]
I am not sure that `Makefile` is a good fit. Why? Because there are two modes for this template: `docker` and local.

And `Makefile` cannot support both options at the same time.
Users can add their own tools to automate this process. Use example provided by @AlwxSin as an inspiration.
