### ISSUE TITLE
Trying to run docker-compose build && docker-compose up gives an error:  test_project exited with code 127

### ISSUE THREAD

**Issue by weholt** [wemake-services/wemake-django-template#661]
Trying to run docker-compose build && docker-compose up gives an error:  test_project exited with code 127. I see ': No such file or directory'sh in the console output and since the error code 127 also is related to unknown command there seem to be something wrong with the dockerfile related to django.

I'm testing this on Windows 10.

**Comment by sobolevn** [comment]
Hey, @weholt! Thanks for using this template and reporting a bug!

Can you please provide a full traceback? 
Since it does work for me and CI: https://travis-ci.org/wemake-services/wemake-django-template

**Comment by soap** [comment]
I have same error. I just create a new project and try docker-compose build and docker-compose run --rm web python manage.py migrate.

![2019-02-09_5-52-57](https://user-images.githubusercontent.com/1073690/52510579-15a91b80-2c2f-11e9-8ebf-b8fc6700139c.png)

**Comment by soap** [comment]
It might be caused by calling sh to run script.

**Comment by sobolevn** [comment]
Can you please dig a little more into this problem? 

1. I don't have an access to windows machine
2. It is not officially supported
3. I do not have any experience with windows at all

**Comment by soap** [comment]
@sobolevn, as I works on Windows machine more than on Linux. I will try to investigate into the problem. I think it is related to Windows 10, or may be Docker on windows or Dockerfile and script files.

If I have more information I will update it here.

**Comment by sobolevn** [comment]
@soap thanks! We can even support Windows as a first-class operating system.
And enable CI builds on windows as well.

**Comment by soap** [comment]
I tried boot2docker on Virtual Box (install docker-composer). So I can run docker using my user and add shared folder of the project to Linux. Unluckily It did not work. It is the same error “cannot find wait-for-command.sh”.

So I think it is a problem of Docker not yours. However I will try my best to figure it out so you can update documentation on the issue.

**Comment by sobolevn** [comment]
@soap thanks a lot! We have "Troubleshooting" section in the docs just for this case.

**Comment by sobolevn** [comment]
@soap how's your research is going? Can this issue be closed?

**Comment by sobolevn** [comment]
Closing as stale. Please, reopen if you still have any issues.
