### ISSUE TITLE
Move ipython to extra dependencies

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#685]
`ipython` is not required anywhere except local machine. Moreover, not all developers use it.
Maybe we can move to some new `extra` dependency section?

We can even create more of them later.

**Comment by DmytroLitvinov** [comment]
Hello @sobolevn .

Personally I, use it at `shell` and `shell_plus` managements commands.
It is very useful, because it has autocomplete and it loads all of the models.

I think we can use it under `dev-dependencies`.

**Comment by DmytroLitvinov** [comment]
I agree with you that it is not required package under main dependecies, but for local machine it is very usefull.
What do you think?

**Comment by sobolevn** [comment]
Same, I just try to find the ways to speed up the `docker` builds inside the CI.

**Comment by sobolevn** [comment]
https://github.com/sdispater/poetry#extras

**Comment by sobolevn** [comment]
```(.venv) ~/Documents/PyCharmProjects/...  master ✗
» poetry install -E ipython
Installing dependencies from lock file


Package operations: 13 installs, 0 updates, 0 removals

  - Installing ipython-genutils (0.2.0)
  - Installing parso (0.3.4)
  - Installing ptyprocess (0.6.0)
  - Installing pygments (2.3.1)
  - Installing wcwidth (0.1.7)
  - Installing appnope (0.1.0)
  - Installing backcall (0.1.0)
  - Installing jedi (0.13.3)
  - Installing pexpect (4.6.0)
  - Installing pickleshare (0.7.5)
  - Installing prompt-toolkit (2.0.9)
  - Installing traitlets (4.3.2)
  - Installing ipython (7.3.0)

(.venv) ~/Documents/PyCharmProjects/...  master ✗
» poetry install -E docs
Installing dependencies from lock file


Package operations: 10 installs, 0 updates, 0 removals

  - Installing pyparsing (2.3.1)
  - Installing alabaster (0.7.12)
  - Installing babel (2.6.0)
  - Installing imagesize (1.1.0)
  - Installing packaging (19.0)
  - Installing sphinxcontrib-websupport (1.1.0)
  - Installing pockets (0.7.2)
  - Installing sphinx (1.8.5)
  - Installing sphinx-autodoc-typehints (1.6.0)
  - Installing sphinxcontrib-napoleon (0.7)```

**Comment by sobolevn** [comment]
There are several problems:
1. `poetry` has bugs related to extras https://github.com/sdispater/poetry/issues/834 and https://github.com/sdispater/poetry/issues/772
2. we need to somehow pass these `--extra` params to `docker` build 
3. this needs to work differently for different envs (so, clearly no `ipython` on prod)

**Comment by sobolevn** [comment]
I will put this on hold for now.
