### ISSUE TITLE
Return regular calls to CI, remove pre-commit

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#689]
This is not something to mix up: `pre-commit` runs locally, CI is a different beast. 
Now I am facing a situation where we have a `pre-commit` hook that should not be executed inside the CI.

**Comment by ffedoroff** [comment]
Hello. Sorry for asking questions in closed issue, but I need some help. It looks like you removed pre-commit support on local development, is it correct? Could you please describe how to run all linters on local development, is it `docker-compose run --rm web sh ./docker/ci.sh`?

**Comment by sobolevn** [comment]
Yes, exactly. 👍
