### ISSUE TITLE
Default site URL announced by docker should not be trusted

### ISSUE THREAD

**Issue by Hiyorimi** [wemake-services/wemake-django-template#692]
Docker on start announces `Starting development server at http://0.0.0.0:8000/`. It is wrong and it is available under  http://127.0.0.1:8000/. This should be reflected somewhere in documentation.

**Comment by AlwxSin** [comment]
@Hiyorimi why do you think this is wrong? Docker-compose forwards 8000 port and that's it.
[Here](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/gunicorn.sh#L28) we start an app on `0.0.0.0` host, so it's available on host machine at `0.0.0.0` **and** `127.0.0.1`

Also, @sobolevn how do you think, should hosts `0.0.0.0` or `127.0.0.1` be in `environments/development.py` under `ALLOWED_HOSTS`?

**Comment by sobolevn** [comment]
@AlwxSin yes, this is the proposed solution from my side as well. `0.0.0.0` should be allowed.

**Comment by Hiyorimi** [comment]
@AlwxSin Running website in docker is not available  at http://0.0.0.0:8000/ at least on Mac. So it causes confusion.

**Comment by AlwxSin** [comment]
@Hiyorimi For me running website in docker **is** available at `http://0.0.0.0:8000/` on Mac. Can you provide more info. What your browser shows you when you open page?

**Comment by Hiyorimi** [comment]
I guess that can be resolved with adding '0.0.0.0' to ALLOWED_HOSTS as default parameter to development settings file. 

Can I do it ?

**Comment by sobolevn** [comment]
@Hiyorimi please, feel free.

**Comment by Hiyorimi** [comment]
I guess @sobolevn won't bet entirely happy with my [PR](https://github.com/wemake-services/wemake-django-template/pull/699), but it's a good start.
