### ISSUE TITLE
Modify Dockerfile and/or ci.sh — Poetry + Docker → Poetry + Docker with Multi-Stage Builds

### ISSUE THREAD

**Issue by hangtwenty** [wemake-services/wemake-django-template#697]
From [an encounter on StackOverflow on the thread, "Integrating Python Poetry with Docker"](https://stackoverflow.com/questions/53835198/integrating-python-poetry-with-docker/54830677#comment97058172_54763270) 😄

----

me:

> Readers of this answer may [care to learn about Docker multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds). I know in my case multi-stage builds greatly simplified the process of base vs test vs app docker images. [See also this post](https://www.lutro.me/posts/python-docker-multi-stage-builds) which is not poetry-specific but shows a reason one might consider continuing to use virtualenv within docker, when doing multi-stage builds. (Not yet tested myself, I've only adopted poetry recently.) 

@sobolevn:

> @hangtwenty are you interested in contributing multi-stage builds to wemake-django-template? It would be an awesome feature that will reduce the final image size. If so, drop me a line on github by creating a new issue, please.

**Comment by hangtwenty** [comment]
I'm swamped but I'll look for some time to contribute this, soon -- I'll be doing this concretely at work, and then it shouldn't be hard to generalize, from there.

**Comment by sobolevn** [comment]
@hangtwenty thanks a lot! 🥇

**Comment by pakal** [comment]
See https://github.com/wemake-services/wemake-django-template/pull/785

**Comment by sobolevn** [comment]
Closed via #785! Thanks!
