### ISSUE TITLE
Add django-admin-env-notice

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#703]
https://github.com/dizballanze/django-admin-env-notice

**Comment by sobolevn** [comment]
https://github.com/dizballanze/django-admin-env-notice/issues/9

**Comment by sobolevn** [comment]
Reopen if the blocking issue is resolved. And I don't think that it will be.

**Comment by DmytroLitvinov** [comment]
@sobolevn, we could manually add it without this package to template.
What do you think?

**Comment by sobolevn** [comment]
The same as in #543 

Bloating projects with un-reusable code is a bad thing. 
Things that we really can do:
1. Fix the project `django-admin-env-notice` by sending a PR
2. Fork it
3. Create our own version
4. Just wait and do nothing

I am fine with any of these options.
