### ISSUE TITLE
Template is not working with Python 3.7 in Ubuntu 18.04

### ISSUE THREAD

**Issue by ffedoroff** [wemake-services/wemake-django-template#710]
I cannot make this template works with python 3.7 on pure Ubuntu 18.04.
To make projects work with particular python version, I usually use one of:
```
virtualenv -p /usr/bin/python3.7 .venv
pipenv --python 3.7
```
But you switched to **poetry** from **pipenv**, and now I don't know how to use poetry without pipenv:
```
poetry install                                                                              
  [RuntimeError]                                                  
  The current Python version (3.6.7) is not supported by the project (^3.7.2)  
  Please activate a compatible Python version. 

pipenv shell
poetry install
  Installing dependencies from lock file...
```
I'm not familiar with poetry, could you please confirm that I still have to use pipenv or virtualenv for python 3.7? Or maybe someone can suggest how to use poetry with python 3.7?

P.S.
Thank you very much for amazing project!

**Comment by sobolevn** [comment]
Hey, @ffedoroff! Thanks for your feedback.

I am still stuck with `3.6` because of `async` keyword issue with `celery`.
To upgrade you will have to do several things:
1. Change `python` version here: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L15
2. Change your base `docker` image here: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/Dockerfile#L1

And it should be working fine. Please, close this issue if that works for you.

**Comment by ffedoroff** [comment]
Hello @sobolevn thank you very much for response.
I have changed those 2 parameters, but unfortunately it doesn't work for me.
The problem is: 
```
python -V # Python 2.7.15rc1
python3 -V # Python 3.6.7
pipenv shell
python3 -V # Python 3.7.3
```
So, as you can see, if I run `poetry install` without `pipenv shell` it uses `Python 3.6.7` but not `Python 3.7.3`
Other words, do you agree, that I still have to use pipenv or virtualenv to make it works with 3.7?

**Comment by sobolevn** [comment]
Why do you use `pipenv` and `poetry` together?

Use just one of them. And `poetry` is better in my experience. 
Here's how it works:

0. Clean up everything
1. `poetry config settings.virtualenvs.in-project true`
2. `poetry install`
3. `source .venv/bin/activate`
4. your local env is ready

But, I still recommend to use `docker` workflow. It is way more predictable.

**Comment by AlwxSin** [comment]
@ffedoroff and if you want use pure Ubuntu I suggest you to look at [pyenv](https://github.com/pyenv/pyenv)

**Comment by sobolevn** [comment]
@ffedoroff one more place to adjust: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L75
