### ISSUE TITLE
Update django to 2.2

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#716]
It is just released: https://docs.djangoproject.com/en/2.2/releases/2.2/

Let's do it!

- [x] Check libraries compatibility with django>=2.2
- [ ] Upgrade source code at project

**Comment by DmytroLitvinov** [comment]
After upgrading, I think it would be nice to promote this awesome template at reddit, medium,  PythonDigest, and other platforms.

**Comment by sobolevn** [comment]
Sure! Any help (including tweets, reddit posts, etc) is highly appreciated. 😊

**Comment by DmytroLitvinov** [comment]
@sobolevn do we have list of items for upgrading?
I would like to start to upgrade this project to 2.2 version.

**Comment by sobolevn** [comment]
Nope, since I have never touched `django@2.2` 😄 

Feel free to research and report your progress.

**Comment by DmytroLitvinov** [comment]
@sobolevn tried to find information about template tag `raw` [here](https://github.com/wemake-services/wemake-django-template/commit/931a773d8d166118010c7d4fda09560d380e6fba), but unsuccessfully. 

Could you please explain where it should take from?
It raises next error:
> django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 1: 'raw'. Did you forget to register or load this tag?

**Comment by DmytroLitvinov** [comment]
Report after brief investigation of upgrading to 2.2 version.

All main packages are compatible with django 2.2, so we need only update local code.
After also brief investigation, it seems that we need to remove `SessionAuthenticationMiddleware` middleware and change `urls` to `path`

**Comment by sobolevn** [comment]
@DmytroLitvinov `raw` is specific to `cookiecutter`. It is required not to parse `django` templates.
It will be removed from the final code.

Upgrade seems easy! Glad to hear it.

**Comment by amiroff** [comment]
Hey! Just fyi, I upgraded locally to 2.2.1 and here is the list of deps required upgrading: 

Package operations: 0 installs, 13 updates, 0 removals

  - pbr (5.1.3 -> 5.2.0)
  - urllib3 (1.24.2 -> 1.24.3)
  - django (1.11.20 -> 2.2.1)
  - isort (4.3.17 -> 4.3.18)
  - testfixtures (6.7.0 -> 6.8.2)
  - zipp (0.3.3 -> 0.4.0)
  - cffi (1.12.2 -> 1.12.3)
  - identify (1.4.1 -> 1.4.2)
  - typed-ast (1.3.1 -> 1.3.5)
  - virtualenv (16.4.3 -> 16.5.0)
  - django-feature-policy (2.0.0 -> 2.1.0)
  - pre-commit (1.15.2 -> 1.16.0)
  - pytest-cov (2.6.1 -> 2.7.1)

**Comment by sobolevn** [comment]
@amiroff does it work for you?

**Comment by amiroff** [comment]
> @amiroff does it work for you?

Yes. migrations, superuser creation and admin all worked after removing unused django.contrib.auth.middleware.SessionAuthenticationMiddleware middleware as per  [2.2 Release Notes](https://docs.djangoproject.com/en/2.0/releases/2.0/#miscellaneous) :+1:

**Comment by sobolevn** [comment]
Done! Django2.2 support is merged. Thanks to @folt!

There would be a period of polishing, but it can be used already.
Last `1.11` release is here: https://github.com/wemake-services/wemake-django-template/releases/tag/django-one
