### ISSUE TITLE
Remove django-referrer-policy

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#719]
It often break, I am not sure that it should be included by default.

**Comment by DmytroLitvinov** [comment]
@sobolevn it is not adopted to Django 1.11.
More detail here: https://docs.djangoproject.com/en/2.1/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

**Comment by sobolevn** [comment]
@DmytroLitvinov invited you to be a collaborator on this project. 🎉

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn .

I did not receive an answer from maintainer of package "django-referrer-policy".
We need to remove it poetry file or better to add this middleware as a native code to project.
What do you think?

**Comment by sobolevn** [comment]
Remove from dependencies. Because I do not want to store any boilerplate in the project.

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn .

Author of package said that he will add support for django 2.2

**Comment by sobolevn** [comment]
Good news!

Then it can be enabled again when #716 will be merged. I plan to work on it this week.
Let's reopen the original issue where I add `django-referrer-policy`.

Related: #543
