### ISSUE TITLE
Add note about `kira-setup`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#734]
We have this awesome little tool to setup Gitlab projects that perfectly matches this template.
It is called `kira-setup` and it is a part of `kira` bots family. 

We can mention it in the docs. Maybe someone will find it useful.
Link: https://github.com/wemake-services/kira-setup

**Comment by DmytroLitvinov** [comment]
It is not clear from docs of `kira-setup` what exactly problem it solves.

**Comment by sobolevn** [comment]
@DmytroLitvinov yeap, I know that 😞 

It is a very quick and dirty release of our internal tool to create Gitlab projects with all the right settings and workflow.

Give it a try on the newly-created project just to get the taste of it.

But, it will be improved in the future. Currently I have more important things to work on.

**Comment by sobolevn** [comment]
Nope, we do not recomment Gitlab anymore and we will eventually completely move off it.

**Comment by DmytroLitvinov** [comment]
Because of last politic news from GitLab?

**Comment by sobolevn** [comment]
Not just it, but this was actually the last nail in the coffin.

All reasons:
1. Very bad user support (I was not able to upgrade my plan in 4! month)
2. Slow development speed and small community
3. Reliability problems, downtimes are frequent. Jobs might be very slow on shared runners and not picked up for a looong time.

Not to forget that racist statements cannot be tolerated.

**Comment by pydolan** [comment]
What are some alternatives you prefer?

**Comment by sobolevn** [comment]
Well, that's the problem: I am not sure yet.
