### ISSUE TITLE
Consider adding django-feature-policy

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#735]
https://pypi.org/project/django-feature-policy/

**Comment by sobolevn** [comment]
Related: https://adamj.eu/tech/2019/04/10/how-to-score-a+-for-security-headers-on-your-django-website/

**Comment by DmytroLitvinov** [comment]
Hello @sobolevn 

I have created PR for this issue: https://github.com/wemake-services/wemake-django-template/pull/739
Do we need to add separate file for this package for settings or maybe add line into `common.py` with next text from [README of package](https://github.com/adamchainz/django-feature-policy#setting)

**Comment by sobolevn** [comment]
@DmytroLitvinov `common.py` is fine. Thanks for your work! 🥇
