### ISSUE TITLE
Mark the language names as translation

### ISSUE THREAD

**Issue by folt** [wemake-services/wemake-django-template#742]
Hi!
Studying your recipe, I noticed that you can improve it a little.
[LANGUAGES](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/components/common.py#L100) not marked for translation.
[Django documentation says it can be marked.](https://docs.djangoproject.com/en/2.2/ref/settings/#languages)
How do you feel about fixing this?

**Comment by DmytroLitvinov** [comment]
Close as https://github.com/wemake-services/wemake-django-template/pull/743 is merged.
