### ISSUE TITLE
Investigate and fix flake8 linting

### ISSUE THREAD

**Issue by DmytroLitvinov** [wemake-services/wemake-django-template#745]
We found that our flake8 does not lint anymore project.

* [Test PR](https://github.com/wemake-services/wemake-django-template/pull/744)
* [Failed build](https://travis-ci.org/wemake-services/wemake-django-template/builds/521323995)

**Comment by sobolevn** [comment]
As you said it can be just `flake8 .`

If it works, that's fine.

**Comment by DmytroLitvinov** [comment]
Fixed in https://github.com/wemake-services/wemake-django-template/pull/757
