### ISSUE TITLE
pytest execution order

### ISSUE THREAD

**Issue by vaad2** [wemake-services/wemake-django-template#754]
open setup.cfg
comment 
`addopts = --doctest-modules`

tests wil fail, because pytest override settings.DEBUG = False, earlier than urls compile

**Comment by sobolevn** [comment]
@vaad2 should we add explicit `setting.DEBUG = True` inside `conftests.py`?

**Comment by sobolevn** [comment]
@vaad2 ping. What's your solution to this problem?
