### ISSUE TITLE
poetry.toml is invalid

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#758]
`a` and `b` should be replaced with project and author's name.
Values are the same as here: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.gitlab-ci.yml#L4-L5

Originally reported by @proofit404

**Comment by DmytroLitvinov** [comment]
https://github.com/wemake-services/wemake-django-template/pull/759

Last time when I tried to do the same, CI was failed.

**Comment by sobolevn** [comment]
The power of CI belongs to me! 
![Sauron](https://vignette.wikia.nocookie.net/lotr/images/3/3a/Sauron.jpg/revision/latest?cb=20120620000759)
