### ISSUE TITLE
pytest doctest not working with custom user model

### ISSUE THREAD

**Issue by vaad2** [wemake-services/wemake-django-template#766]
Django 2.2, python 3.7.3
- create test app
- put into main/models.py
`from django.contrib.auth.models import AbstractUser`
`class User(AbstractUser):
    pass
`

run pytest

_server/apps/main/models.py:6: in <module>
    class User(AbstractUser):
.venv/lib/python3.7/site-packages/django/db/models/base.py:111: in __new__
    "INSTALLED_APPS." % (module, name)
E   RuntimeError: Model class main.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS._

because DoctestModule.collect set wrong name for module - _main.models,_ instead _server.apps.main.models_

**Comment by sobolevn** [comment]
@vaad2 hey, thanks for your report. But, `django@2.2` is not officially supported yet.

**Comment by sobolevn** [comment]
Please, try again. We now support `django@2.2`! 

Reopen if something goes wrong.
