### ISSUE TITLE
Add Trivy - scanner for containers

### ISSUE THREAD

**Issue by DmytroLitvinov** [wemake-services/wemake-django-template#780]
[Trivy](https://github.com/knqyf263/trivy) - A Simple and Comprehensive Vulnerability Scanner for Containers, Suitable for CI

**Comment by sobolevn** [comment]
Sorry, but it does not fit our CI model. It can be only listed as an external dependency in the "Security" section.

@DmytroLitvinov are you willing to put this together in a PR?

**Comment by DmytroLitvinov** [comment]
Hello @sobolevn ,

Yes, I will add it to security section.
I am going to assign it to myself and will prepare PR.
