### ISSUE TITLE
Caddy and Django HSTS max-ages differ

### ISSUE THREAD

**Issue by davidfischer** [wemake-services/wemake-django-template#799]
In Caddy, you have HSTS set to a year:

    header / Strict-Transport-Security "max-age=31536000;"

But in Django you have HSTS set to 6 days:

    SECURE_HSTS_SECONDS = 518400

Recommended minimum values differ a bit but range from a month to 6 months with a year being the most common recommendation. It is possible that somebody might want a short value during an initial rollout, but I think at least a warning should be present with the Django settings as 6 days is definitely too short for a production.

**Comment by sobolevn** [comment]
Yes, that's a bug. Caddy has a correct amount. Will you please fix it with a pr? 🙂

**Comment by davidfischer** [comment]
I'm not actually using this template so I will leave it for users to fix. I was just calling out an issue where I saw it.
