### ISSUE TITLE
Enhancement: replace docker entrypoint by naked "tini"

### ISSUE THREAD

**Issue by pakal** [wemake-services/wemake-django-template#806]
The custom entrypoint makes the VM launch quite fragile, if the postgres container has troubles or volume mounting fails (frequent on docker-tools for windows), the VM crash or loops very quicly (due to missing "sleep 1" in wait routine).

Maybe it's possible to launch it as is with just "tini", but to prefix commands in the docker-compsoe by the said "wait for postgres" calls (which would be scripts added to machine in Dockerfile) ?

**Comment by sobolevn** [comment]
Sorry, this is not in scope. In cases this problem will be reported by other users as well, I might reconsider this feature.
