### ISSUE TITLE
"env: can't execute 'sh ': No such file or directory" on docker "web" startup

### ISSUE THREAD

**Issue by pakal** [wemake-services/wemake-django-template#807]
I lack time to dig this issue, but on docker-tools on windows, at docker (or docker-compose) launch the "web" container displays this error, as if the linxu alpine image didn't have the "sh" binary referenced by the custom entrypoint script.

Overriding the entrypoint with docker's "--entrypoint" argument always works on the other hand, even when asking for "sh".

I open this issue in case other people have the problem too and have an idea what's going on.

https://github.com/wemake-services/wemake-django-template/issues/806 would solve the problem as a side effect

**Comment by sobolevn** [comment]
My wild guess: we have this shebang https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/entrypoint.sh#L1

Can you please try to modify it to `/bin/sh`?

**Comment by pakal** [comment]
Thanks for the suggestion, I tried with a full path, it failed too, with other errors (even "file not found").

It ended up being that the cookie-cutter checkout had replaced linux newlines by windows newlines, despite the global "autocrlf = input" of my Git config. So the sh command had an invisible "\r" next to it, and was not found...  Hope this might help other windows users around.

**Comment by sobolevn** [comment]
I am reopening just to research possible solutions later.
Thanks for reporting!

**Comment by sobolevn** [comment]
Counting as solved.
