### ISSUE TITLE
Consider adding django-pg-zero-downtime-migrations

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#810]
https://github.com/tbicr/django-pg-zero-downtime-migrations

**Comment by AlwxSin** [comment]
We thought about it and they are several cons
* you should use balancer and more than one instance of an application to make a profit from zero-downtime-migrations
* you can't effectively use another DB backends such as `django-postgres-extra` for upserts
* for every migration you should open the library docs and carefully check which operations it can do and which can't

And only one pro - zero-downtime.
