### ISSUE TITLE
.tox thoughts

### ISSUE THREAD

**Issue by chexex** [wemake-services/wemake-django-template#820]
I've noticed that `.tox` is mentioned in a [couple of projects files](https://github.com/wemake-services/wemake-django-template/search?q=tox&unscoped_q=tox).

I want to figure out whether it is a good idea to have matrix tests in this template or not.

My case:
I bootstrapped a project which is a pluggable package with common Django project structure. It is supposed that the package will be used with either different Django versions and different python versions.

I've already started conversation with @sobolevn and he gave me his point of view:
Since Django projects are being written for the specific python version, python version is fixed in .pyproject.toml, Dockerfile, docs.

Although I completely understand this point, I want other developers to share their thoughts on the question above.

Thanks a lot.  

PS: i'm opening the issue with Nikita's permission :-).

**Comment by sobolevn** [comment]
Some thoughts on this:

> I've noticed that .tox is mentioned in a couple of projects files.

Yes, that's true. Mostly `tox` is mentioned in `.gitignore` and config files to ignore it from the project. It should not mislead users.

> I bootstrapped a project which is a pluggable package with common Django project structure. It is supposed that the package will be used with either different Django versions and different python versions.

That's a completely different use-case. We have this in several projects, where we test that our package works well with the existing `python` + `django` combinations. Examples: 
- https://github.com/dry-python/mappers
- https://github.com/dry-python/dependencies
- https://github.com/sobolevn/django-split-settings

But, this project provides not just the simplest project structure that is needed for the tests, it also provides a lot of other stuff that is not needed for tests (like `docker`, docs, linters, mypy, etc)
So, I recommend to use something similar like in the examples above.

Other opinions are welcome! Please, share your thoughts!

**Comment by sobolevn** [comment]
Let's mark it as solved for now. Reopen if any you have any other questions about `.tox`.
