### ISSUE TITLE
Django-csp breaks Django Debug Toolbar

### ISSUE THREAD

**Issue by amiroff** [wemake-services/wemake-django-template#825]
Out of the box development.py contains these config lines which in my case were not enough to satisfy DDT.

    CSP_SCRIPT_SRC = ("'self'", 'ajax.googleapis.com')
    CSP_IMG_SRC = ("'self'", 'data:')

Simply toggling DDT SQL pane in admin results in endless loading screen and JS console  fails compaining with 

    Refused to connect to 'http://127.0.0.1:8000/__debug__/render_panel/?store_id=12fd90bd00994e7d80f63f46f1f0ae6d&panel_id=SQLPanel' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

I've managed to fix this by adding `CSP_DEFAULT_SRC = ("'self'", 'ajax.googleapis.com')` to environments/development.py but again, being no master with CSP wanted to report this anyways as there could be a misconfiguration.

PS: Local development.

**Comment by sobolevn** [comment]
Fixed: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/environments/development.py#L61
