### ISSUE TITLE
Consider adding PYTHONOPTIMIZE

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#845]
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONOPTIMIZE

This will remove `assert` from code. And will possibly make the app faster.

**Comment by sobolevn** [comment]
It will break a lot of stuff. People use `assert` for logic.

**Comment by AlwxSin** [comment]
> People use `assert` for logic

Which is insane. Maybe for developing it's ok, but in production, there should be no asserts.
