### ISSUE TITLE
Open port for db service

### ISSUE THREAD

**Issue by folt** [wemake-services/wemake-django-template#877]
I want to start in the container only the service with the database given. However, by default it does not listen on port 5432. It may be worth opening it. `docker-compose up -d db`  
This will make it possible to run the database separately from the rest of the infrastructure.

**Comment by sobolevn** [comment]
Sorry, we won't support that in the template. It might open ports on production services, promote bad practices, and confuse users.

In case you need it in your project - no problem! Just edit the configuration the way you like.

Thanks for the suggestion! :+1:
