### ISSUE TITLE
.gitlab-ci.yml is syntaxically invalid

### ISSUE THREAD

**Issue by tkrugg** [wemake-services/wemake-django-template#927]
Hi there, 
I've generated a template and immediately uploaded it to gitlab. But it looked like the gitlab-ci file was invalid and the build failed. Anything I'm doing wrong?

![Untitled (2)](https://user-images.githubusercontent.com/2982512/67244580-4a29d400-f45a-11e9-9eef-af961b3ee569.gif)

**Comment by sobolevn** [comment]
The problem is that https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.gitlab-ci.yml#L4 was not changed for you.

Can you please show how your template was generated?

**Comment by sobolevn** [comment]
Feel free to reopen if this continues to happen.

**Comment by DmytroLitvinov** [comment]
> To validate your GitLab CI configurations, go to 'CI/CD → Pipelines' inside your project, and click on the 'CI Lint' button.
 (c) [GitLab](https://docs.gitlab.com/ce/ci/yaml/README.html#validate-the-gitlab-ciyml)
