### ISSUE TITLE
Add a link to django-admin tutorial

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#943]
https://books.agiliq.com/projects/django-admin-cookbook/en/latest/

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,

Would you like to add it [this section](https://wemake-django-template.readthedocs.io/en/latest/pages/template/django.html#further-reading)?

**Comment by sobolevn** [comment]
Yeap, with new header: `Admin`
