### ISSUE TITLE
Replace `flake8 **/*.py` to `flake8 .` in linters.rst

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#960]
https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docs/pages/template/linters.rst

**Comment by DmytroLitvinov** [comment]
Closed in https://github.com/wemake-services/wemake-django-template/commit/2ca455a86db1c510b843522055efbb4089421902

**Comment by sobolevn** [comment]
Thanks a lot! 👍
