### ISSUE TITLE
Enforce 100 of code to be covered by default

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#962]
https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L68

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,

What the reason to have 100% instead of 90%?
Could you please share your thoughts on it?

**Comment by sobolevn** [comment]
It is better to cover everything than not to.
We internally use different metric from 95% to 100%, but never 90%

That's just a more realistic value.
