### ISSUE TITLE
Consider using `--cache-from`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#977]
Build times are so high because of all this `poetry` stuff. I hope to make it a bit faster.

https://docs.docker.com/engine/reference/commandline/build/

**Comment by AlwxSin** [comment]
Here is my current multistage Dockerfile with poetry for example.

```dockerfile
FROM python:3.7.4-alpine3.10 as builder

ARG DEVELOPMENT_BUILD=false

ENV PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /src

RUN apk add --no-cache gcc make musl-dev libffi-dev libressl-dev git

RUN pip install -U pip==19.2.2
RUN pip install poetry==1.0.0b3

ADD pyproject.toml poetry.lock /src/
RUN poetry export \
        --format requirements.txt \
        --output requirements.txt \
        --without-hashes \
        $(test "$DEVELOPMENT_BUILD" = "true" && echo "--dev")

RUN apk add --no-cache postgresql-dev \
 && mkdir /wheels \
 && pip wheel -r requirements.txt --wheel-dir /wheels

FROM python:3.7.4-alpine3.10

ENV PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_INDEX=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

WORKDIR /src

COPY --from=builder /wheels /wheels
RUN apk add --no-cache libpq libssl1.1 \
 && pip install /wheels/*

COPY . .

ENTRYPOINT [ "/src/bin/run.sh" ]
```

**Comment by sobolevn** [comment]
@AlwxSin this is more about `.gitlab-ci.yml` and its cache.
On the other hand, I am not going to use Gitlab pretty soon (due to their politics and some lacking features).

So, this feature is about reusing layer's cache from the previous builds.

**Comment by sobolevn** [comment]
Related:
- https://gitlab.com/gitlab-org/gitlab-foss/issues/17861
- https://docs.docker.com/compose/compose-file/#cache_from

**Comment by sobolevn** [comment]
`--cache-from` conflicts with multi-stage builds: https://github.com/moby/moby/issues/34715
https://github.com/moby/buildkit/blob/master/README.md#inline-push-image-and-cache-together

**Comment by sobolevn** [comment]
Related:
- https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84
- https://gitlab.com/snippets/185782

**Comment by sobolevn** [comment]
Ok, I've made it.
<img width="1051" alt="Снимок экрана 2019-11-27 в 18 42 54" src="https://user-images.githubusercontent.com/4660275/69737643-cd1f0800-1145-11ea-8bfe-d4cdd6933bf3.png">

🎉 🎉 🎉

**Comment by sobolevn** [comment]
Build one for dev: https://gitlab.com/wemake.services/test_project/-/jobs/489412848
Build two for prod: https://gitlab.com/wemake.services/test_project/-/jobs/489413767

Ready to be merged back.
