### ISSUE TITLE
Additional notes on other recommended code quality tools

### ISSUE THREAD

**Issue by dashmug** [wemake-services/wemake-django-template#982]
> Our code quality defined by this template is minimally acceptable. We know tools to make it even better. But they are not included. Since they are literally hardcore.

I support your choice in making the template minimal. I'm interested what other tools you guys recommend that you just didn't include in the template. Maybe adding notes in the docs page may be useful.

**Comment by sobolevn** [comment]
Hi, @dashmug! Thanks for your interest.

We have two lists of linters that are not included:
- https://wemake-django-template.readthedocs.io/en/latest/pages/template/linters.html#linters-that-are-not-included
- https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/extras.html

These lists contains pretty much everything we have. And these links can be found in the docs.
What else I can help you with?

**Comment by sobolevn** [comment]
Closed as resolved, feel free to reopen 🙂
