### ISSUE TITLE
pyclean from ci.sh deletes all static

### ISSUE THREAD

**Issue by wwarne** [wemake-services/wemake-django-template#989]
Running 
`find . | grep -E '(__pycache__|.static|\.py[cod]$)' | xargs rm -rf`
is not only deleting all cache files and `.static` dir which we used for `collectstatic --dry-run` command but also deletes all files inside your `static` directories, because `.` in regexp matches any character.
So it would delete, for example:

> ./server/apps/main/static/main/css/index.css
> ./server/apps/main/static/images
> ./server/apps/main/static/images/favicon-16x16.png
> ./server/apps/main/static/images/favicon-32x32.png

It's not good if you want to run `ci.sh` not only on CI but on your local machine too. (I would love to do it to check my code before commit).

Based on ci.sh content I suggest it should only delete `.static` directory, so to fix this problem we can  change '.static' to '\\.static' in the regexp.

**Comment by sobolevn** [comment]
Oh no! Sorry!

Fixing it.
